### ISSUE TITLE
Plugin uses stale outputFile

### ISSUE THREAD

**Issue by eleventigers** [KeepSafe/dexcount-gradle-plugin#40] opened 2016-01-12 15:58 UTC
Since 0.3.1 (more specifically [commit](https://github.com/KeepSafe/dexcount-gradle-plugin/commit/4a1220a08350f2fb62832ebfd94daa6178b7cd4a)) the [outputFile](https://github.com/KeepSafe/dexcount-gradle-plugin/commit/4a1220a08350f2fb62832ebfd94daa6178b7cd4a#diff-cf1f32ad0e792fe8e4ea6875f9262fc3R51) that gets used to report dexcount will be stale if user rewrites apk name with `applicationVariants.all { variant -> ... }` logic.

**Comment by benjamin-bader** [comment] 2016-01-12 17:14
Interesting.  I was wondering if we'd see problems from that commit - I guess we do!  Thanks for reporting.

Can you please post a build script and commandline invocation that reproduces the problem?  I'm pretty sure that I've used this kind of apk name rewriting without having this problem in the past, and haven't been able to reproduce it.

**Comment by benjamin-bader** [comment] 2016-01-25 18:29
Seems to be identical to issue #46, which I can reproduce and confirm.

**Comment by benjamin-bader** [comment] 2016-01-26 19:21
I think this is fixed in the latest snapshot build; would you please try again using 0.4.1-SNAPSHOT and confirm?

**Comment by eleventigers** [comment] 2016-01-28 17:57
Hey @benjamin-bader the 0.4.1-SNAPSHOT seems to work fine for me ;]

**Comment by benjamin-bader** [comment] 2016-01-28 21:49
Awesome, thanks!

**Closed by benjamin-bader** 2016-01-28 21:49 UTC

**Comment by benjamin-bader** [comment] 2016-01-29 19:31
FYI, version 0.4.1 (including this bugfix) is now available in Maven Central, or it will be in an hour or two.
