### ISSUE TITLE
[AGP 3.6.0-alpha03] - com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File;

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#267] opened 2019-06-10 01:42 UTC
## Example build:
https://github.com/jaredsburrows/android-gif-example/pull/103

## Error:
```
$ gradlew assembleDebug
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

FAILURE: Build failed with an exception.

* What went wrong:
com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 798ms
```

**Comment by benjamin-bader** [comment] 2019-06-10 02:19
Thanks for the report!  They sure do like to change things up with that API, don't they.

**Comment by jaredsburrows** [comment] 2019-06-10 02:20
Yeah. Sadly :(

**Comment by benjamin-bader** [comment] 2019-06-18 17:33
I looked in to this a little over the weekend and am a bit flummoxed; your build is using 3.6.0-alphaN.  The only place in our code where we access the deprecated methods is actually in the `LegacyTaskProvider` which _should_ only be used for AGP versions less than 3.0.0.  I suspect that something is different with the version-comparision code, but haven't had time to dig in.

FWIW, I spoke too quickly about the API changes; these are the same deprecations from the last major release.  It's just something wonky with our version checks/their version number.

**Comment by ChristianBecker** [comment] 2019-08-31 11:06
Any progress on this?

**Comment by benjamin-bader** [comment] 2019-08-31 20:01
None whatsoever - would be happy to have any help you're able to offer.

**Comment by ychescale9** [comment] 2019-09-01 10:20
I've spent some time on this and it appears to me that the problem itself is caused by the `ApkVariantOutput.getPackageApplication` API in **AGP 3.6** not being binary compatible with previous versions of AGP (dexcount-gradle-plugin currently uses 3.3).

I've made some changes in [my fork](https://github.com/ychescale9/dexcount-gradle-plugin/tree/yc/diagnose-3.6.0-issue) to prove this with an integration test:

- Added a fixture project (copied from `integration`) - `src/test/fixtures/integration`
- Added an integration test - `src/test/kotlin/com/getkeepsafe/dexcount/DexMethodCountPluginFunctionalTest`
- Added `runtimeOnly "com.android.tools.build:gradle:3.6.0-alpha09"` to simulate that the consumer is using **AGP 3.6.0** alongside the plugin in the integration test.
- The integration test `integrationTestsAndroid` will fail with the same error: `com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File`

To "fix" the problem:

- I changed the compileOnly AGP dependency to "com.android.tools.build:gradle:3.6.0-alpha09"
- Fixed the breaking in `Plugin.kt` at line 371.
- The integration test now passes

I don't understand why **compiling** with a new version of AGP would fix the issue though :confused:

Note that changing AGP to 3.6.0 breaks most of the tests as `task.execute` was removed in Gradle 5.0, and AGP 3.6.0 requires Gradle 5.5+. So it's a can of worm :joy:. Until we migrate to the `TaskProvider` API we'll probably continue to suffer from this kind of issues. But then what versions of Gradle / AGP do we want to continue to support?

**Comment by benjamin-bader** [comment] 2019-09-02 02:39
Hey, thanks for the thorough investigation!  At some point I think we have to bid _adieu_ to AGP < 3.0; I haven't given much thought to Gradle versions since (with some notable exceptions) it's pretty simple to support most of them.  I don't feel great about deprecating support for AGP 3.0 or above, but don't have any data to support that feeling.

I'd be curious if, after your fix, the plugin still works on projects using older versions of AGP?

**Comment by ychescale9** [comment] 2019-09-02 08:49
Unfortunately it doesn't. This is all due to that breaking change in **`PackageAndroidArtifact.java`** introduced in 3.6.0 that we use for assigning to the `inputFileProvider` in `applyToApkVariant(variant: ApkVariant)`.

Pre-3.6.0:

```java
@OutputDirectory
public File getOutputDirectory() {
    return outputDirectory;
}
```

3.6.0
```java
@OutputDirectory
public abstract DirectoryProperty getOutputDirectory();
```

And thus this exception when you compile the plugin with AGP 3.6.0 but use AGP-3.5.0 at runtime:

`java.lang.NoSuchMethodError: com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Lorg/gradle/api/file/DirectoryProperty;`

I don't know how we can support both pre and post 3.6.0 unless we can do the same thing with some non-breaking API. E.g. the `ThreeThreeProvider` just uses `output.outputFile` but I don't know if we can use it for 3.6.0+.

Is it possible to setup the project to `compileOnly` with both 3.5.0 and 3.6.0 without classpath conflicts so we can create a separate plugin for 3.6.0+? Or perhaps it's time to consider having multiple development branches?

**Comment by benjamin-bader** [comment] 2019-09-03 00:46
I guess we'll have to make a `ThreeSixProvider`, then!  I'll see if I can fit that in this week.

**Closed** 2019-09-06 16:34 UTC
