### ISSUE TITLE
Not support renamed output file

### ISSUE THREAD

**Issue by msdx** [KeepSafe/dexcount-gradle-plugin#46] opened 2016-01-25 08:51 UTC
Build failed if I rename the output file like this:
```
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def file = output.outputFile
            def name = "xxx" + variant.name + "-v" + defaultConfig.versionName + ".apk";
            output.outputFile = new File(file.parent, name)
        }
    }
```

log:
```
Execution failed for task ':app:assembleDevelopDebug'.
> /workspace/project/park-here-android/app/build/outputs/apk/app-Develop-debug.apk (没有那个文件或目录)
```

**Comment by benjamin-bader** [comment] 2016-01-25 18:20
Thanks for the report.  It seems like this is caused by #32, and we'll need to think harder about how to fix this.

**Comment by benjamin-bader** [comment] 2016-01-26 19:21
I think this is fixed in the latest snapshot build; would you please try again using `0.4.1-SNAPSHOT` and confirm?

**Comment by msdx** [comment] 2016-01-27 02:35
@benjamin-bader I'd like to. Has this version be published?

**Comment by benjamin-bader** [comment] 2016-01-28 04:41
Yes; it has been published to Sonatype's snapshot repo.  Instructions for using snapshots are in the readme, let me know if you need help.  I'd like to confirm that this fixes the issue before making a final release.

**Comment by msdx** [comment] 2016-01-28 06:57
I couldn't find `0.4.1-SNAPSHOT` in jcenter or mavenCentral...

**Comment by msdx** [comment] 2016-01-28 07:48
@benjamin-bader It works. ^_^

**Comment by benjamin-bader** [comment] 2016-01-28 21:49
Nice!  Thank you!

**Closed by benjamin-bader** 2016-01-28 21:49 UTC

**Comment by benjamin-bader** [comment] 2016-01-29 19:30
FYI, version 0.4.1 (including this bugfix) is now available in Maven Central, or it will be in an hour or two.
