### ISSUE TITLE
inputFile does not exist

### ISSUE THREAD

**Issue by MinkiPan** [KeepSafe/dexcount-gradle-plugin#223] opened 2017-10-21 09:12 UTC
Android Studio 3.0 RC2

Error:A problem was found with the configuration of task ':app:countDebugDexMethods'.
> File '/Users/mingkangpan/Documents/app/build/outputs/apk/debug/app-debug.apk' specified for property 'inputFile' does not exist.

am I missing something?

**Comment by ychescale9** [comment] 2017-10-23 13:10
I'm guessing you are customizing the apk name by setting the `outputFileName` in the variant outputs? the plugin doesn't seem to recognize that as the apk file to perform the task on.
You can try something like `setProperty("archivesBaseName", "YourCustomName-$versionName")` instead.

**Comment by MinkiPan** [comment] 2017-10-23 20:13
aahhhh I see, I have this config

>     applicationVariants.all { variant ->
>         variant.outputs.all { output ->
> 
>             def outputPath = '../.'
>             def outputName = "app-${variant.buildType.name}.apk"
>             outputFileName = new File(outputPath, outputName)
>         }
>     }

how do I fix this?

**Comment by ychescale9** [comment] 2017-10-24 01:46
This is the same issue as #220.

**Comment by ychescale9** [comment] 2017-10-24 02:01
@MinkiPan so you don't want the flavor in your apk name and you want your generated apk in the parent directory which is `outputs` rather than `apk`?
I don't think you can achieve that with `archivesBaseName` so whether you can do this probably depends on whether there will be new api in the new Android gradle plugin 3.0 to support that and how the dexcount plugin uses the new api in the future. See #220

**Comment by MinkiPan** [comment] 2017-10-24 08:56
okay I see thanks, another question is there a way to configure this plugin only for a specific build variant? because I don't want to waste any time on generating dex count statistic while I am developing

**Comment by ychescale9** [comment] 2017-10-24 10:07
You can disable the task for specific variant:
`afterEvaluate {
    tasks.each { task ->
        if (task.name == "countDevDebugDexMethods") {
            task.enabled = false
        }
    }
}`
where `dev` is a product flavor and `debug` is build type.
But the plugin should have minimum impact on build time.

**Comment by MinkiPan** [comment] 2017-10-24 11:19
I did it with gradle properties

```
boolean applyDexCount = hasProperty('applyDexCount')
if (applyDexCount) {
    // make sure this line comes *after* you apply the Android plugin
    apply plugin: 'com.getkeepsafe.dexcount'
}

```

**Comment by MinkiPan** [comment] 2017-10-24 11:20
and actually we can close this issue :)

**Comment by benjamin-bader** [comment] 2017-11-30 22:34
Hi, I've just pushed a new build (version 0.8.2) to Maven Central, which ought to address this bug.  It will be available within the next 5 minutes; please let me know whether it solves your problem.

**Comment by ened** [comment] 2017-12-01 10:30
The same issue appears when Android Studio builds only a single ABI (like arm64-v8a), but the App supports multiple ABIs. In that case, the plugin knows the correct APK filename, but fails to handle the case when the `inputFile` does not exist.

```
Error:FAILURE: Build completed with 4 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':app:countDevelopmentDebugDevelopment-armeabi-v7a-debugDexMethods'.
> File '/project/app/build/outputs/apk/development/debug/Project-1.0-100-development-armeabi-v7a-debug.apk' specified for property 'inputFile' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
```

**Comment by benjamin-bader** [comment] 2017-12-04 07:25
While the "file not found" message is similar, this is due to a very different cause - in your case, it seems like Android Studio is being clever in a way that's new to me.  I haven't yet figured out it is telling Gradle only to build one ABI, but I don't imagine it be that hard to suss out.

**Comment by benjamin-bader** [comment] 2017-12-07 02:00
@ened I'm trying to reproduce the failure you're seeing, but cannot.  To help debug this issue, would you please:
1. Share your build.gradle, specifically the part where you define your ABI splits/flavors/etc
2. Tell me exactly how your are getting Android Studio to build such that the error is triggered

Thanks!

**Comment by benjamin-bader** [comment] 2017-12-11 18:06
Closing this as a non-reproducible issue not related to the original reported by MinkiPan.

If you still have problems, please open a new issue, include a `build.gradle`, and list steps to reproduce the failure.

**Closed by benjamin-bader** 2017-12-11 18:07 UTC
